name: Deploy

on:
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: "0 6 * * 1"  # 06:00-UTC every Monday
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency: 
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate Docker Metadata (Tags and Labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            prefix=
            suffix=
            latest=false
          tags: |
            type=schedule,pattern={{date 'YYYY-MM-DD'}}
            type=raw,event=schedule,value=latest,enable={{is_default_branch}}
            type=raw,event=ref,value=latest,enable={{is_default_branch}}
            type=sha
            type=sha,format=long

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Test Dev Container
        uses: devcontainers/ci@v0.2
        with:
          imageName: devcontainer-base
          imageTag: base
          push: never
          runCmd: |
            python --version

      - name: Publish Image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: BASE=devcontainer-base
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
